name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ibiqlik/action-yamllint@v3

    - run: rustup toolchain install 1.65 --profile minimal
    - run: rustup component add clippy
    - uses: Swatinem/rust-cache@v2

    - name: Lint
      run: cargo clippy -- -D warnings

    - name: Test
      run: cargo test --all

    - name: Build
      run: cargo build --release
