name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - uses: ibiqlik/action-yamllint@v3

    - run: rustup toolchain install 1.65 --profile minimal
    - run: rustup component add clippy
    - uses: Swatinem/rust-cache@v2

    - name: Lint
      run: cargo clippy -- -D warnings

    - name: Test
      run: cargo test --all

  build:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-apple-darwin, x86_64-unknown-linux-musl]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - run: apt-get -y install libfontconfig1-dev

    - name: Set Cargo.toml version
      shell: bash
      run: |
        mv Cargo.toml Cargo.toml.orig
        sed "s/0\\.0\\.0-git/$(git describe --tags)/" Cargo.toml.orig >Cargo.toml
        mv Cargo.lock Cargo.lock.orig
        sed "s/0\\.0\\.0-git/$(git describe --tags)/" Cargo.lock.orig >Cargo.lock

    - name: Build
      id: build
      uses: rust-build/rust-build.action@v1.4.0
      with:
        RUSTTARGET: ${{ matrix.target }}
        TOOLCHAIN_VERSION: "1.65"
        UPLOAD_MODE: none

    - uses: actions/upload-artifact@v3
      with:
        path: ${{ steps.build.outputs.BUILT_ARCHIVE }}
