name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - uses: ibiqlik/action-yamllint@v3

    - uses: Swatinem/rust-cache@v2
    - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.65
          override: true
          components: clippy

    - name: Lint
      run: cargo clippy -- -D warnings

    - name: Test
      run: cargo test --all

  build:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            suffix: ''
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: ''
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            suffix: .exe
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: Swatinem/rust-cache@v2
    - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.65
          override: true
    - uses: actions-rs/cargo@v1
        with:
          command: install
          args: toml-cli

    - shell: bash
      run: |
        mv Cargo.toml Cargo.toml.orig
        toml set Cargo.toml.orig package.version "$(git describe --tags)" > Cargo.toml

    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

    - uses: actions/upload-artifact@v3
      with:
        name: rbr-sync-${{ matrix.target }}
        path: ./target/release/rbr-sync${{ matrix.suffix }}
