name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-apple-darwin]
    steps:
    - uses: actions/checkout@v3
    - name: Set Cargo.toml version
      shell: bash
      env:
        RELEASE_TAG: ${{ github.ref }}
      run: |
        mv Cargo.toml Cargo.toml.orig
        sed "s/0\\.0\\.0-git/${RELEASE_TAG##*\/v}/" Cargo.toml.orig >Cargo.toml
        mv Cargo.lock Cargo.lock.orig
        sed "s/0\\.0\\.0-git/${RELEASE_TAG##*\/v}/" Cargo.lock.orig >Cargo.lock
    - name: Compile and release
      uses: rust-build/rust-build.action@v1.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        RUSTTARGET: ${{ matrix.target }}
        TOOLCHAIN_VERSION: "1.65"
