name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: Swatinem/rust-cache@v2
    - run: cargo install toml-cli

    - shell: bash
      run: |
        mv Cargo.toml Cargo.toml.orig
        toml set Cargo.toml.orig package.version "$(git describe --tags)" > Cargo.toml

    - run: cargo build --release

    - uses: dlemstra/code-sign-action@v1
      with:
        # https://stackoverflow.com/a/47144138
        certificate: "${{ secrets.CERTIFICATE }}"
        password: "${{ secrets.CERTIFICATE_PASSWORD }}"
        files: ./target/release/rbr-sync.exe
        description: "rbr-sync"

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./target/release/rbr-sync.exe
