name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: Swatinem/rust-cache@v2
    - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.65
          override: true
    - uses: actions-rs/cargo@v1
        with:
          command: install
          args: toml-cli

    - shell: bash
      run: |
        mv Cargo.toml Cargo.toml.orig
        toml set Cargo.toml.orig package.version "$(git describe --tags)" > Cargo.toml

    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./target/release/rbr-sync.exe
